name: .NET Pack

on:
  workflow_call:
    inputs:
      version:
        description: The version of your NuGet package, e.g., 1.0.0.
        required: true
        type: string
      projects:
        description: Optional path to the project(s) file to build. Supports globbing. Default is an empty string.
        required: false
        type: string
        default: ''
      configuration:
        description: Defines the build configuration. Default is Debug.
        required: false
        type: string
        default: 'Debug'
      include-preview:
        description: When set to true, includes preview versions of .NET. Default is false.
        required: false
        type: boolean
        default: false
      verbosity-level:
        description: Sets the verbosity level of the command. Allowed values are quiet, minimal, normal, detailed, and diagnostic. Default is quiet.
        required: false
        type: string
        default: 'quiet'
      download-build-artifact-pattern:
        description: The pattern to download the build artifacts. Default, when left empty, is 'format('*-{0}', inputs.configuration)'.
        required: false
        type: string
        default: ''
      upload-packed-artifact:
        description: Upload the created NuGet packages. Default is to not upload.
        required: false
        type: boolean
        default: false
      upload-packed-artifact-name:
        description: The name of the NuGet package to upload. Default, when left empty, is 'format('NuGet-{0}', inputs.configuration)'.
        required: false
        type: string
        default: ''
      restore-cache-key:
        description: When set, the current workspace will be overwritten with the content of the restore cache. Default is an empty string.
        required: false
        type: string
        default: ''
      timeout-minutes:
        description: The maximum time in minutes to allow the job to run. Default is 15 minutes.
        required: false
        type: number
        default: 15

jobs:
  pack:
    name: 📦 Pack
    runs-on: ubuntu-24.04
    timeout-minutes: ${{ inputs.timeout-minutes }}
    steps:
      - name: Install .NET
        uses: codebeltnet/install-dotnet@v2
        with:
          includePreview: ${{ inputs.include-preview }}

      - name: Pack for ${{ inputs.configuration }}
        uses: codebeltnet/dotnet-pack@v2
        with:
          configuration: ${{ inputs.configuration }}
          level: ${{ inputs.verbosity-level }}
          uploadPackedArtifact: ${{ inputs.upload-packed-artifact }}
          uploadPackedArtifactName: ${{ inputs.upload-packed-artifact-name }}
          version: ${{ needs.build.outputs.version }}
          projects: ${{ inputs.projects }}
          restoreCacheKey: ${{ inputs.restore-cache-key }}
          downloadBuildArtifactPattern: ${{ inputs.download-build-artifact-pattern }}
